kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: ms-rtc-validate-swap-process
  namespace: service-dev-services
spec:
  scaleTargetRef:
    kind: Deployment
    name: ms-rtc-validate-swap-process
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80